/* tslint:disable */
/* eslint-disable */
// @generated
// This file was automatically generated and should not be edited.

import { ProfitLogType } from './../../../../types/globalTypes.d'

// ====================================================
// GraphQL fragment: DoHardWorkFields
// ====================================================

export interface DoHardWorkFields_transaction {
  __typename: 'Transaction'
  /**
   * transaction hash
   */
  id: string
  timestamp: any
  blockNumber: any
  blockHash: any
  from: any
  to: any | null
  value: any
  gasUsed: any
  gasPrice: any
}

export interface DoHardWorkFields_strategy_transaction {
  __typename: 'Transaction'
  /**
   * transaction hash
   */
  id: string
  timestamp: any
  blockNumber: any
  blockHash: any
  from: any
  to: any | null
  value: any
  gasUsed: any
  gasPrice: any
}

export interface DoHardWorkFields_strategy {
  __typename: 'Strategy'
  /**
   * strategy address
   */
  id: string
  /**
   * timestamp strategy was registered on the vault
   */
  timestamp: any
  /**
   * transaction strategy was registered on the vault
   */
  transaction: DoHardWorkFields_strategy_transaction
  /**
   * aggregated profit generated by strategy
   */
  aggregatedProfit: any
  /**
   * aggregated fee for profit sharing
   */
  aggregatedFee: any
}

export interface DoHardWorkFields_sharePriceChangeLog {
  __typename: 'SharePriceChangeLog'
  /**
   * transaction hash
   */
  id: string
  /**
   * share price before do hardwork
   */
  oldSharePrice: any
  /**
   * share price after do hard work
   */
  newSharePrice: any
}

export interface DoHardWorkFields_profitLog {
  __typename: 'ProfitLog'
  /**
   * transaction hash
   */
  id: string
  /**
   * type of profit log event
   */
  type: ProfitLogType
  /**
   * profit amount
   */
  profitAmount: any
  /**
   * fee for profit share
   */
  feeAmount: any
}

export interface DoHardWorkFields {
  __typename: 'DoHardWork'
  /**
   * transaction hash
   */
  id: string
  timestamp: any
  transaction: DoHardWorkFields_transaction
  /**
   * strategy that was used for hardwork
   */
  strategy: DoHardWorkFields_strategy
  /**
   * price per full share after do hard work
   */
  pricePerFullShare: any
  /**
   * balance in vault at time of hard work
   */
  balanceInVault: any
  /**
   * balance in vault including invested portion
   */
  balanceWithInvestment: any
  /**
   * event associated with share price change emitted by controller
   */
  sharePriceChangeLog: DoHardWorkFields_sharePriceChangeLog | null
  /**
   * profit log associated with do hard work - note that it might not exist
   */
  profitLog: DoHardWorkFields_profitLog | null
}
