/* tslint:disable */
/* eslint-disable */
// @generated
// This file was automatically generated and should not be edited.

import { ProfitLogType } from './../../../../types/globalTypes.d'

// ====================================================
// GraphQL fragment: VaultFields
// ====================================================

export interface VaultFields_transaction {
  __typename: 'Transaction'
  /**
   * transaction hash
   */
  id: string
  timestamp: any
  blockNumber: any
  blockHash: any
  from: any
  to: any | null
  value: any
  gasUsed: any
  gasPrice: any
}

export interface VaultFields_currStrategy_transaction {
  __typename: 'Transaction'
  /**
   * transaction hash
   */
  id: string
  timestamp: any
  blockNumber: any
  blockHash: any
  from: any
  to: any | null
  value: any
  gasUsed: any
  gasPrice: any
}

export interface VaultFields_currStrategy {
  __typename: 'Strategy'
  /**
   * strategy address
   */
  id: string
  /**
   * timestamp strategy was registered on the vault
   */
  timestamp: any
  /**
   * transaction strategy was registered on the vault
   */
  transaction: VaultFields_currStrategy_transaction
  /**
   * aggregated profit generated by strategy
   */
  aggregatedProfit: any
  /**
   * aggregated fee for profit sharing
   */
  aggregatedFee: any
}

export interface VaultFields_strategies_transaction {
  __typename: 'Transaction'
  /**
   * transaction hash
   */
  id: string
  timestamp: any
  blockNumber: any
  blockHash: any
  from: any
  to: any | null
  value: any
  gasUsed: any
  gasPrice: any
}

export interface VaultFields_strategies {
  __typename: 'Strategy'
  /**
   * strategy address
   */
  id: string
  /**
   * timestamp strategy was registered on the vault
   */
  timestamp: any
  /**
   * transaction strategy was registered on the vault
   */
  transaction: VaultFields_strategies_transaction
  /**
   * aggregated profit generated by strategy
   */
  aggregatedProfit: any
  /**
   * aggregated fee for profit sharing
   */
  aggregatedFee: any
}

export interface VaultFields_underlying {
  __typename: 'Token'
  /**
   * token address
   */
  id: string
  name: string
  symbol: string
  decimals: number
}

export interface VaultFields_fToken {
  __typename: 'Token'
  /**
   * token address
   */
  id: string
  name: string
  symbol: string
  decimals: number
}

export interface VaultFields_currPool {
  __typename: 'Pool'
  /**
   * pool address
   */
  id: string
}

export interface VaultFields_doHardWorks_transaction {
  __typename: 'Transaction'
  /**
   * transaction hash
   */
  id: string
  timestamp: any
  blockNumber: any
  blockHash: any
  from: any
  to: any | null
  value: any
  gasUsed: any
  gasPrice: any
}

export interface VaultFields_doHardWorks_strategy_transaction {
  __typename: 'Transaction'
  /**
   * transaction hash
   */
  id: string
  timestamp: any
  blockNumber: any
  blockHash: any
  from: any
  to: any | null
  value: any
  gasUsed: any
  gasPrice: any
}

export interface VaultFields_doHardWorks_strategy {
  __typename: 'Strategy'
  /**
   * strategy address
   */
  id: string
  /**
   * timestamp strategy was registered on the vault
   */
  timestamp: any
  /**
   * transaction strategy was registered on the vault
   */
  transaction: VaultFields_doHardWorks_strategy_transaction
  /**
   * aggregated profit generated by strategy
   */
  aggregatedProfit: any
  /**
   * aggregated fee for profit sharing
   */
  aggregatedFee: any
}

export interface VaultFields_doHardWorks_sharePriceChangeLog {
  __typename: 'SharePriceChangeLog'
  /**
   * transaction hash
   */
  id: string
  /**
   * share price before do hardwork
   */
  oldSharePrice: any
  /**
   * share price after do hard work
   */
  newSharePrice: any
}

export interface VaultFields_doHardWorks_profitLog {
  __typename: 'ProfitLog'
  /**
   * transaction hash
   */
  id: string
  /**
   * type of profit log event
   */
  type: ProfitLogType
  /**
   * profit amount
   */
  profitAmount: any
  /**
   * fee for profit share
   */
  feeAmount: any
}

export interface VaultFields_doHardWorks {
  __typename: 'DoHardWork'
  /**
   * transaction hash
   */
  id: string
  timestamp: any
  transaction: VaultFields_doHardWorks_transaction
  /**
   * strategy that was used for hardwork
   */
  strategy: VaultFields_doHardWorks_strategy
  /**
   * price per full share after do hard work
   */
  pricePerFullShare: any
  /**
   * balance in vault at time of hard work
   */
  balanceInVault: any
  /**
   * balance in vault including invested portion
   */
  balanceWithInvestment: any
  /**
   * event associated with share price change emitted by controller
   */
  sharePriceChangeLog: VaultFields_doHardWorks_sharePriceChangeLog | null
  /**
   * profit log associated with do hard work - note that it might not exist
   */
  profitLog: VaultFields_doHardWorks_profitLog | null
}

export interface VaultFields_withdrawals_transaction {
  __typename: 'Transaction'
  /**
   * transaction hash
   */
  id: string
  timestamp: any
  blockNumber: any
  blockHash: any
  from: any
  to: any | null
  value: any
  gasUsed: any
  gasPrice: any
}

export interface VaultFields_withdrawals_user {
  __typename: 'User'
  /**
   * address of user account
   */
  id: string
}

export interface VaultFields_withdrawals {
  __typename: 'Withdrawal'
  id: string
  timestamp: any
  transaction: VaultFields_withdrawals_transaction
  user: VaultFields_withdrawals_user
  amount: any
}

export interface VaultFields_deposits_transaction {
  __typename: 'Transaction'
  /**
   * transaction hash
   */
  id: string
  timestamp: any
  blockNumber: any
  blockHash: any
  from: any
  to: any | null
  value: any
  gasUsed: any
  gasPrice: any
}

export interface VaultFields_deposits_user {
  __typename: 'User'
  /**
   * address of user account
   */
  id: string
}

export interface VaultFields_deposits {
  __typename: 'Deposit'
  id: string
  timestamp: any
  transaction: VaultFields_deposits_transaction
  user: VaultFields_deposits_user
  amount: any
}

export interface VaultFields {
  __typename: 'Vault'
  /**
   * address of the vault
   */
  id: string
  /**
   * timestamp vault was registered at the controller
   */
  timestamp: any
  /**
   * transaction vault was registered at the controller
   */
  transaction: VaultFields_transaction
  /**
   * current strategy
   */
  currStrategy: VaultFields_currStrategy
  /**
   * all strategies
   */
  strategies: VaultFields_strategies[]
  /**
   * token locked up in vault
   */
  underlying: VaultFields_underlying
  /**
   * returned share token
   */
  fToken: VaultFields_fToken
  /**
   * most recent pool as detected by NotifyHelper is usually not null
   */
  currPool: VaultFields_currPool | null
  /**
   * hard work done on vault
   */
  doHardWorks: VaultFields_doHardWorks[]
  withdrawals: VaultFields_withdrawals[]
  deposits: VaultFields_deposits[]
}
